#!/usr/bin/env php
<?php

use Zuno\DI\Container;
use Zuno\Console\Command;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
Container::setInstance($app);

$console = new Application();
$console->setCatchExceptions(true);

Command::dispatch($console);

$status = $console->run();

exit($status);
